### ISSUE TITLE
Don't use `@debug` in test

### ISSUE THREAD

**Issue by w-vi** [apiaryio/dredd-hooks-template#2]
Use `@announce` instead of `@debug` as `@debug` is possibly buffering or otherwise tempering with the output and tests even though valid may fail.

**Comment by gonzalo-bulnes** [comment]
I confirm that `@debug` makes our test suite fail as soon as we use Aruba >= v0.7.0, the `@announce` tag, on the other hand works fine.

Besides, **for debugging purpose**, the `@announce` tag is much more verbose (read: useful)!

**Comment by honzajavorek** [comment]
Closed by #9.
