### ISSUE TITLE
Cucumber tests assume that TCP server will emit a "Starting" message on stdout

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/dredd-hooks-template#5]
...but this thing is not documented anywhere.
See [this code](https://github.com/apiaryio/dredd-hooks-template/blob/master/features/tcp_server.feature#L5)

**Comment by netmilk** [comment]
I thought [this line](https://github.com/apiaryio/dredd-hooks-template/blob/master/features/tcp_server.feature#L5) in the Cucumber feature is self-documenting enough, but good point @XVincentX! Let's add it to Dredd's doc how to add new language!

**Comment by netmilk** [comment]
Filed a pull request in Dredd doc: https://github.com/apiaryio/dredd/pull/334
